### PR TITLE
Interactive set_key

### PR DESCRIPTION
**Pull request by eliocamp**
This is a possible version of what we talked in #11.

### CODE REVIEW

**Comment by khufkens** [comment]
I was looking through the changes and figured that I can't accept this pull request as is, the CDS api keys are 36 characters long not 34 as with the webapi. I'm also not sure if this value is, or will remain, static over time for either CDS or ECMWF API.

To make this future proof I would suggest writing a `wf_check_login()` function which tests if you can login using the credentials provided on either system (ECMWF webapi or CDS). 

You could use wf_user_info() to see if the query passes for ECMWF and a call to https://cds.climate.copernicus.eu/api/v2 requires credentials while not returning data (good for verification of service). Internally you can query this url using `wf_server(service = "cds")`.

Let me know if I should take it from here, or if you want to have a go at it?

**Comment by khufkens** [comment]
Sorry for being picky about these things, but I like to take the long look when developing so hard coding values might come back to bite you.

**Comment by eliocamp** [comment]
No need to apologise! 
I'll give it a go and see what I can do.

**Comment by khufkens** [comment]
Thanks, much appreciated! btw. add yourself to the DESCRIPTION file as a contributor. Credit where credit is due.

**Comment by khufkens** [comment]
FYI For a style guide and general code advice I try to stick to this:

https://ropensci.github.io/dev_guide/

**Pull request closed without merging**
