### PR TITLE
Added CDS and ECMWF mars support, quite substantial changes

### PR DESCRIPTION
**Pull request by retostauffer**
Hey Koen

I've finished extending/testing/documenting the package. Overall there is quite a lot of new stuff (`cds_*` alternatives to `wf_*` wherever needed) and some modifications of the existing `wf_*` functions such all different data sets/sources can be processed.

**Major changes**:

- Added Climate Data Store support (`cds_request`, `cds_set_key`, `cds_get_key`)
- Added support for both, `~/.ecmwfapirc` user-definition files (`wf_*`; for ECMWF requests) and `~/.cdsapirc` user-definitions (`cds_*`; for CDS requests). All functions can be called by either using an explicit `email` or `user` (uses keyring) or `email = NULL`/`user = NULL` (tries to read the `~/.*apirc` files).
- Added ECMWF mars support (for member state/commercial user accounts). Used when `dataset = "mars"` is specified.
- Thus, moved the _R_ package `keyring` from 'Depends' to 'Suggests'.
- Add a CDS vignette (`vignettes/cds_vignette.Rmd`).
- R checks look fairly ok (except tests not running, see below).

**Testing**:

- I've added some scripts `tests/downloads_.*.R` which are not intended to run as tests. Some requests require a member-state/commercial  user account and can take up to an hour. These are more scripts I use/used to see if everything works.
- Testthat: I do have some problems running your examples as they use `wf_get_key("<your_email_address>")`. I've written some additional tests (`tests/testthat/test_cds.R`) using two environment variables with my user settings (`CDSAPIKEY`, `CDSAPIUSER`). Not sure what's the best way to go here!

**Vignettes**:

- Not enough experiences myself: for now I set all my examples to `eval FALSE`. Just in case.

**Open issues/todos/questions**:

- I do have some things t.b.d., might open github issues later on.

Not sure what's the best way to go from here on, any chance you'll have a quick look and give some feedback, or how should be proceed?

Greez and thanks,
R

### CODE REVIEW

**Comment by retostauffer** [comment]
Should have had done the pull-request after fixing travis/testthat :). Sorry for all the commits!

Travis-CI still fails due to some small things. Missing font might be related to some markdown-formatting but I should grab myself another coffee and go to work now!

All best so far,
R

**Comment by khufkens** [comment]
Hi Reto,

Thanks for these wonderful additions. I'm not going to merge yet as I've got a few concerns I want to talk through.

One is something I mentioned in an issue regarding authentication. I really love the use of legacy .rc files however I feel we should not encourage their use. As I mentioned I think we should use the keyring consistently (which simplifies all download functions) as it is the proper way to handle login keys. However, having it automatically populated from legacy .rc files seems convenient and will smooth the transition for a lot of users. It does break with the python package, but I feel the use of keys in this setup leaves a lot to be desired. I don't think it should be our intention to replicated bad design decisions for the sake of consistency.

I've seen a lot of replication in your code as well. I therefore would suggest to merge most if not all `cds_*()` functions into their respective `wf_*()` functions by using a "service" argument of sorts. Surprisingly you did so for `wf_transfer()` using the "type" argument, but didn't carry this through to other functions although complexity is low enough to merit it I feel.

Sticking to the `wf_*` notation will also make the package compliant with the newer R naming conventions. These use a prefix of a package, wf for weather forecast in this case, followed by a descriptive verb or noun. The simple features package for example uses sf_*. This setup avoids namespace issues where the names of functions are similar across packages. Let me know what you think. I think using only this limited set of functions across services will make things easier (this is in a way also what is missing in the current python setup - no centralized way to query all ECMWF data - while not technically hard!).

I'll see if I can merge this pull into a branch rather than master to continue my development along these lines.

**Comment by retostauffer** [comment]
Perfect, thanks! 

"_ I'm not going to merge yet as I've got a few concerns I want to talk through._": that's why we have these features, and please don't hurry, it would be a nice to have in the near future, but for now I'm fine with my python scripts.

"_I don't think it should be our intention to replicated bad design ..._": as mentioned in the other comment this is more than fine for me. I just went the way I am used to, but I agree with your input (drop the whole key-from-file stuff, users should add the login once).

"_I've seen a lot of replication ..._": sorry, my bad :). I started with a full parallel chain as I did not know how different the code will be at the end. But there _is_ indeed a strong overlap. Interpreted "`wf_`" as weather forecast, and CDS is reanalysis, for me the separation made sense from this perspective, but I think we should merge it and write some custom handlers for the `POST`, `GET`, `DELETE` and "check http response" parts. Might be relatively simple, **I can also do that** but maybe not this week :).

"_Sticking to the `wf_*` ..._": absolutely fine. If it would have been `ec_*` I might have tried to merge, thought that `wf_*` is a special set of methods :). But -> merging them absolutely makes sense (as mentioned above).

Happy to help if possible/needed/useful!

**Comment by khufkens** [comment]
The `wf_` prefix was rather ad hoc, yet remains connected to the products I feel. The difference between forecast and re-analysis might not be clear for all, but I guess for all intents and purposes it is good enough.

I've pulled your branch and I'm pulling things into the `wf_` functions where necessary. I might agree with you on dropping the rc file issue, dropping the functions altogether. Support on OSX and Windows should be good, Linux can be trickier, depends on how things are configured.

**Pull request merged**
